---
# vars file for roles/gui-base
dropbox_rpm_url: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2019.02.14-1.fedora.x86_64.rpm
zoom_rpm_url: https://zoom.us/client/latest/zoom_x86_64.rpm

wayland_packages:
  # wayland and the wayland x server are installed as part of the base Fedora Workstation install
  #- wayland
  #- xorg-server-xwayland
  - sway
  - swayidle
  - swaylock
  - wofi
  - light
  - scdoc # Not actually required for wayland but required for building `mako`

gui_packages:
  - gdm
  - [ gnome-keyring, libsecret, seahorse ] # things like skype require this or they won't remember credentials
  - firefox
  # Fedora doesn't package Chrome because it's proprietary.  Google offers an RPM download but it's manual; not clear how to automate
  #- google-chrome
  - chromium
  - terminator
  - w3m
  - dmenu
  - rofi
  - conky
  - playerctl
  - pavucontrol
  - network-manager-applet
  #- networkmanager-dmenu-git
  - blueberry
  - qemu
  - gnome-boxes
  - dunst
  - xss-lock
  - [ redshift, redshift-gtk ]
  # waybar doesn't have a package yet but it does have a lot of dependencies
  - [
      meson,
      ninja-build,
      jsoncpp-devel,
      libinput-devel,
      libwayland-client,
      wayland-devel,
      wayland-protocols-devel,
      gtkmm30-devel,
      libdbusmenu-gtk3-devel,
      libsigc++,
      fmt-devel,
      wlroots,
      libdbusmenu-gtk3,
      libmpdclient,
      spdlog-devel,
      libnl3,
      libnl3-devel,
      pulseaudio-libs-devel,
      libudev-devel,
      libmpd-devel
      libappindicator-devel,
      libappindicator-gtk3-devel
  ]
  - tk # for i8kutils
  - glxinfo
  - nautilus
  - rdesktop
  - [ freerdp, remmina ]
  - [ cups, system-config-printer, foomatic, foomatic-db, foomatic-db-ppds, foomatic-db-filesystem ]
  - gnome-shell-extension-appindicator
  - libatomic # This seems to be a dependency of dropbox

theme_packages:
  - arc-theme
  - adapta-gtk-theme
  - gnome-icon-theme
  - moka-icon-theme

wine_packages:
  - wine
  - wine-mono
  - openal
  - libxml2
  - mpg123
  - lcms2
  - giflib
  - libpng
  - gnutls
  - cups-libs
  - winetricks
  - samba
  - sane-backends # office 2016 needs this
  - pygtk2 #technically this is a CrossOver dependency

flatpak_packages:
  - com.skype.Client
  - com.slack.Slack
  - com.spotify.Client
